name: todolist-prod

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_PROFILE=prod
      - POSTGRES_USER=admin
      - POSTGRES_DB=todolist
      - POSTGRES_PASSWORD=admin
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=todolist
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432
volumes:
  db-data:
networks:
  spring-postgres:
